#!/usr/bin/env bash
# source: https://github.com/petobens/dotfiles/commit/c21c306660142d93d283186210ad9d301a2f5186

tmux ls -F'#{session_id}' | while read -r s; do
	S=$(tmux ls -F'#{session_id}#{session_name}: #{T:tree_mode_format}' | grep ^"$s")
	session_info=${S##$s}
	session_name=$(echo "$session_info" | cut -d ':' -f 1)
	if [[ -n "$1" ]] && [[ "$1" == "$session_name" ]]; then
		echo -e "\033[1;${BMUX_TREE_ACTIVE_COLOR}m$session_info\033[0m"
	else
		echo -e "\033[1;${BMUX_TREE_INACTIVE_COLOR}m$session_info\033[0m"
	fi
	tmux lsw -t"$s" -F'#{window_id}' | while read -r w; do
		W=$(tmux lsw -t"$s" -F'#{window_id}#{T:tree_mode_format}' | grep ^"$w")
		echo "  ${BMUX_TREE_SYMBOL} ${W##$w}"
	done
done
